#230 AWS SQS Support
b2wdigital/async-worker pull request #231
Opened 2020-09-13 04:16 UTC by diogommartins

Ainda to bem no começo, mas minha intenção é que esse PR sai pra hacktoberfest ! :P 
Todos os pitacos são muito bem vindos !!!

2020-09-13 16:40 UTC, daltonmatos requested changes
Tá ficando massa!! 🎉 

Agora é começar a implementar o `SQSRouteEntryPointImpl` para registrar as rotas no `routes_registry` da app e depois implementar o SignalHandler (`SQS`) para efetivamente dar boot no consumer.

E implementar o consumer também. Aqui, por enquanto, teremos algumas lógicas "duplicadas", por exemplo a lógica de encher o `Bucket` para só depois chamar o handler. No futuro podemos talvez pensar em generalizar essas partes e poder ter um "core" para implementar consumer "bufferizados", ou seja, que acumulam mensagens antes de chamar o handler. Mas isso é futuro. =D

2020-09-13 16:40 UTC, daltonmatos commented on Pipfile.lock
> -        "dataclasses": {
Importante fazer o `pipenv install` sempre usando py3.6. Se não fizermos isso algumas dependências (que não são mais necessárias nos pythons mais novos, mas ainda são no py3.6) são removidas e o projeto passa a ficar quebrado no py3.6. Exemplos dessas deps são `dataclasses`, `idna-ssl`.

Pra corrigir aqui basta remover o `.lock` e re-gerar usando py3.6

2020-09-13 16:40 UTC, daltonmatos commented on asyncworker/connections.py
> +    region: str = getenv("AWS_DEFAULT_REGION")
Aqui talvez valha mover os `getenv` para o `asyncworker.conf.Settings` (por ser uma opção geral) e usar aqui `conf.ASYNCWORKER_SQS_DEFAULT_*`, uma option pra cada um dos valores.

As opções de outros backends (HTTP, AMQP, por exemplo) também estão lá.

2020-09-13 16:40 UTC, daltonmatos commented on asyncworker/options.py
> +    NOOP = auto()
Qual o cotexto do `NOOP` no mundo do `SQS`? O que significa escolher `NOOP` como ação a ser executada em cada mensagem após o processamento?

2020-09-13 16:40 UTC, daltonmatos commented on asyncworker/routes.py
> +class SQSRouteOptions(AMQPConnection):
Aqui vale mover essa classe para um pacote próprio: `asyncworker.sqs.*`. Esse objeto poderia estar em `asyncorker.sqs.options`. Aí decidimos se ele será sempre importado de lá ou fazemos também um atalho para ser possível fazer `from asyncworker.sqs import SQSRouteOptions`.

Hoje está tudo dentro do `asyncworker.routes` apenas por uma questão histórica e não dá pra tirar o que está lá hoje imediatamente por causa de algumas dependências circulares, mas como esse é um backend novo acho que já vai dar pra deixar separado.



Outro ponto, acho que essa herança não deveria vir de `AMQPConnection` né?

2020-09-13 16:40 UTC, daltonmatos commented on asyncworker/routes.py
> +
O mesmo aqui, iria pra dentro do pacote `asyncworker.sqs.*`.

2020-09-13 16:50 UTC, daltonmatos commented on asyncworker/routes.py
> +    max_number_of_messages: int = Field(
Será que vale chamar esse campo de `prefetch`? =D Assim para todos os backends que fazem uso da ideia de fila usariam uma nomenclatura consistente.

2020-09-13 16:53 UTC, diogommartins commented on Pipfile.lock
> -        "dataclasses": {
Puts... valeu! Não tinha reparado nisso, cara ! Vou refazer meu venv com py3.6 !

2020-09-14 17:49 UTC, diogommartins commented on asyncworker/routes.py
> +    max_number_of_messages: int = Field(
Boa sacada! Pelo menos um `alias`, vale! Não removeria totalmente `max_number_of_messages` porque é o nome usado pelo ReceiveMessage na [API do SQS](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html#MaxNumberOfMessages), então acho válido manter o mesmo nome pra facilitar o uso de quem está acostumado com o SQS

2021-05-08 19:52 UTC, closed without merging